# Numpy operations with matrices

In this notebook, we will learn about a few numpy features to deal with matrices. 

## Transpose

The transpose of an $m \times n$ matrix $A$ is defined as the $n \times m$ matrix $A^T$ where $A_{ij} = A^T_{ji}$.

In [3]:
import numpy as np

A = np.array([[1, 2],
     [3, 4],
    [5,6],
    [7,8]])

# print("A = \n", A, "\n\nAT = \n", np.transpose(A))
print("A = \n", A, "\n\nAT = \n", A.T)

A = 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]] 

AT = 
 [[1 3 5 7]
 [2 4 6 8]]


## Triangular matrices

A square matrix $A = (a_{ij})$ is called upper triangular if $a_{ij} = 0$ for all $i < j$. 
A square matrix $A = (a_{ij})$ is called lower triangular if $a_{ij} = 0$ for all $i > j$. 

Numpy can convert a square matrix into an upper or lower triangular matrix using the tril() or triu() functions.

In [5]:
B = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("B = \n", B)
print("BL = \n", np.tril(B))
print("BU = \n", np.triu(B))

B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
BL = 
 [[1 0 0]
 [4 5 0]
 [7 8 9]]
BU = 
 [[1 2 3]
 [0 5 6]
 [0 0 9]]


## Diagonal matrix

A diagonal matrix $A = (a_{ij})$ is one for which $a_{ij} = 0$ for all $i \neq j$. A diagonal matrix need not be a square matrix in general. 

The diag function of Numpy can extract the diagonal vector from a matrix, and also produce a diagonal matrix from a vector. 

In [6]:
print("A = \n", A)
ad = np.diag(A)
print("Diagonal vector of A = \n", ad)

print("B = \n", B)
bd = np.diag(B)
print("Diagonal vector of B = \n", bd)

A = 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Diagonal vector of A = 
 [1 4]
B = 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Diagonal vector of B = 
 [1 5 9]


Now converting the diagonal vectors into diagonal matrices.

In [8]:
DA = np.diag(ad)
print(DA)
print("\n")
DB = np.diag(bd)
print(DB)

[[1 0]
 [0 4]]


[[1 0 0]
 [0 5 0]
 [0 0 9]]


## Inverse of a matrix

An $n\times n$ square matrix $A$ is called <i>invertible</i> if there exists another $n\times n$ matrix $B$ such that $A B = I_n$, the $n\times n$ identity matrix. When $A$ is considered to be a linear transformation from $\mathbb{R}^n \to \mathbb{R}^n$, $B$ is the inverse transformation of $A$. The matrix $B$ is called the inverse of $A$, and vice versa. 

<b>However, not all square matrices are invertible.</b>

In [11]:
A = np.array([[1, 1],[0, 2]])
print("A = \n", A)

A1 = np.linalg.inv(A)
print("A1 = \n", A1)

A = 
 [[1 1]
 [0 2]]
A1 = 
 [[ 1.  -0.5]
 [ 0.   0.5]]


## Trace 

The trace of a square matrix is the sum of its diagonal entries. 

In [ ]:
print("B = \n", B)
print("trace(B) = ", np.trace(B))

## Rank

The rank of a matrix is the number of linearly independent rows or columns (the minimum of the two) in it. Intuitively, it is the number of dimensions the vectors in the matrix can span. 

In [15]:
B = np.array([[1, 2, 3, 4, 5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print("B = \n", B)
print("rank(B) = ", np.linalg.matrix_rank(B))

v = np.array([1,2,3,4,7])

print(np.dot(B, v))

B = 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
rank(B) =  2
[ 65 150 235 320 405]


In [18]:
A = np.array([[1, 2],
              [3, 4],
              [5,6],
              [7,8]])
print(A.T)
print("rank(A) = ", np.linalg.matrix_rank(A))

[[1 3 5 7]
 [2 4 6 8]]
rank(A) =  2
