# Numpy Arrays (1-D and 2-D)

This notebook is to discuss operations using Numpy arrays. 

In [17]:
# Let us create a 2-D array

import numpy as np

A = np.array([[1, 2],
     [3, 4],
    [5,6],
    [7,8]])

print(A)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## Array indexing

Accessing an element in the 2-D array is done by index [i,j] for the element in the $i$-th row and the $j$-th column. The indices start from 0.

In [18]:
print(A[2,1])
print(A[0,0])

6
1


## Array slicing

A slice of an array is a part of it. 

For 1-D arrays, a slice can be specified by specifying the [from:to] index, including the from index and excluding the to index, separated by the colon. If no from and to are specified, it refers to the whole array.

In [19]:
import numpy as np

a = np.array([0,10,20,30,40,50])

print("The whole array as a slice:", a[:])
print("The array from index 1 to until 3:", a[1:3])

The whole array as a slice: [ 0 10 20 30 40 50]
The array from index 1 to until 3: [10 20]


#### Using negative index

Specifying a negative index in slicing means count from the end. The index -3 means third from the last element. 

A slicing with a negative index works analogously. 

In [20]:
print("The third element from the end is:", a[-3])

The third element from the end is: 30


In [21]:
print("The array from the third last element till the end is:", a[-3:])
print("The array from the beginning until the last element is:", a[:-1])

The array from the third last element till the end is: [30 40 50]
The array from the beginning until the last element is: [ 0 10 20 30 40]


### Slicing a 2-D array

Slicing a 2-D array works in a similar way, by specifying range of indices for the rows and columns. 

In [33]:
print(A)

#print("The 1st column of A:", A[:,0])
#print("The 2nd row of A:", A[1,:])
#print("The first three rows of A:\n", A[:3,:])
#print("The last three rows of A:\n", A[-3:,:])

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]


#### Specifying a subset of the indices

Instead of a contiguous range of indices, any arbitrary subset (subsequence, in any order) of indices can also be specified. 

In [52]:
A = np.array([[1, 2, 3, 4],
     [3, 4, 5, 6],
    [5,6, 7, 8],
    [7,8, 9, 10],
    [9, 10, 11, 12]])

print(A)

rows = np.array([2,4,0])
cols = np.array([1,3,0])
#rows2 = np.array([3,2])
#print("The 1st and 3rd row of A:\n", A[rows1,:])
print(A[rows,:])
#B = A[rows,:]
#print(B[:,cols])
#print("The matrix in the new ordering of rows:\n", A[rows,:])

[[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]
[[ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  2  3  4]]


## Shape 

The shape attribute returns the shape of an array. For 1-D arrays, it is just the length, given by the number of rows. For 2-D arrays, it is the number of rows and columns. 

In [53]:
print("Shape of a:", a.shape)
print("Shape of A:", A.shape)

# Just getting number of rows or columns
print("Number of rows in A:", A.shape[0])
print("Number of columns in A:", A.shape[1])

Shape of a: (6,)
Shape of A: (5, 4)
Number of rows in A: 5
Number of columns in A: 4


## Reshaping

Reshaping the data is an operation useful in many cases. Reshape works in many ways. 

An 1-D array of length $n$ can be reshaped into a 2-D array ($n \times 1$ or $1 \times n$). 

In [57]:
print(a.shape)
print(a)
#a2D = a.reshape(a.shape[0],1)
#print(a2D.shape)
#print(a2D)
a2D = a.reshape(1,a.shape[0])
print(a2D.shape)
print(a2D)

(6,)
[ 0 10 20 30 40 50]
(1, 6)
[[ 0 10 20 30 40 50]]


### More flexible reshaping

Or, it can be reshaped into $m \times k$ so that $m \times k = n$.

In [60]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[ 0 10]
 [20 30]
 [40 50]]
(3, 2)


### Reshaping 2-D arrays

Similarly, a 2-D array can be reshaped. The elements are ordered row-wise. 

In [67]:
print("Original shape:", A.shape, "\n", A)

B = A.reshape(4,5)
print("Reshaped:", B.shape, "\n", B)

#B = A.reshape(20,3) 
# will produce an error. 
# Total number of elements in the original array must be the same. 

Original shape: (5, 4) 
 [[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]
Reshaped: (4, 5) 
 [[ 1  2  3  4  3]
 [ 4  5  6  5  6]
 [ 7  8  7  8  9]
 [10  9 10 11 12]]


# Broadcasting

Mathematically, matrices can be added or multiplied only if they match in dimensions in certain ways. However, for convenience of coding, Numpy provides the power of conceptually duplicating elements of smaller arrays to match the dimensions of bigger arrays according to the operation required. This is called <i>broadcasting</i>.

## Adding a scalar with an array 

If a scalar is added to an array, it is added to each element of the array. 

In [69]:
print("A = \n", A)
print("A + 3 = \n", (A+3))

A = 
 [[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]
A + 3 = 
 [[ 4  5  6  7]
 [ 6  7  8  9]
 [ 8  9 10 11]
 [10 11 12 13]
 [12 13 14 15]]


### 1-D and 2-D arrays

An 1-D array of shape (n,) can be added to a 2-D array of shape (m,n). The 1-D array here is treated as a row vector which is added to all the rows of the 2-D array. However, an 1-D array of shape (n,) cannot be added to a 2-D array of shape (n,m). 

In [73]:
a1 = np.array([20,30,40,50])
print(a1)
print(a1.shape)
print("A = \n", A)
print("A + a1 = \n", (A+a1))

[20 30 40 50]
(4,)
A = 
 [[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]
A + a1 = 
 [[21 32 43 54]
 [23 34 45 56]
 [25 36 47 58]
 [27 38 49 60]
 [29 40 51 62]]


### 2-D arrays

To add a column vector of size m to each column of a 2-D array A of shape (m,n), we need to add a 2-D array of shape (m,1) to A.

In [76]:
a2 = np.array([[100],[110],[120],[130],[140]])
print(a2.shape, A.shape)
print("a2 = \n", a2)
print("A = \n", A)
print("A + a2 = \n", (A+a2))

(5, 1) (5, 4)
a2 = 
 [[100]
 [110]
 [120]
 [130]
 [140]]
A = 
 [[ 1  2  3  4]
 [ 3  4  5  6]
 [ 5  6  7  8]
 [ 7  8  9 10]
 [ 9 10 11 12]]
A + a2 = 
 [[101 102 103 104]
 [113 114 115 116]
 [125 126 127 128]
 [137 138 139 140]
 [149 150 151 152]]


In [79]:
print(A * a2)

[[ 100  200  300  400]
 [ 330  440  550  660]
 [ 600  720  840  960]
 [ 910 1040 1170 1300]
 [1260 1400 1540 1680]]
