In [1]:
import torch

In [3]:
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print(x*y)

tensor([10.,  3.])


In [4]:
x = torch.zeros([2,5])

In [5]:
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [6]:
x.shape

torch.Size([2, 5])

In [7]:
y = torch.rand([2,5])

In [8]:
y

tensor([[0.9998, 0.0396, 0.8568, 0.7574, 0.2887],
        [0.7243, 0.8747, 0.6497, 0.3049, 0.9714]])

In [9]:
y.view([1,10])

tensor([[0.9998, 0.0396, 0.8568, 0.7574, 0.2887, 0.7243, 0.8747, 0.6497, 0.3049,
         0.9714]])

In [10]:
y = y.view([1,10])

In [11]:
y

tensor([[0.9998, 0.0396, 0.8568, 0.7574, 0.2887, 0.7243, 0.8747, 0.6497, 0.3049,
         0.9714]])

# Datasets

In [12]:
import torch
import torchvision
from torchvision import transforms,datasets

In [13]:
train = datasets.MNIST("",train=True,download=True,transform = transforms.Compose([transforms.ToTensor()]))

test = datasets.MNIST("",train=False,download=True,transform = transforms.Compose([transforms.ToTensor()]))

31.0%IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)

91.6%IOPub message rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_msg_rate_limit`.

Current values:
NotebookApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
NotebookApp.rate_limit_window=3.0 (secs)



102.8%


Extracting MNIST\raw\train-labels-idx1-ubyte.gz to MNIST\raw



100.0%


Extracting MNIST\raw\t10k-images-idx3-ubyte.gz to MNIST\raw



112.7%

Extracting MNIST\raw\t10k-labels-idx1-ubyte.gz to MNIST\raw

Processing...
Done!



C:\Users\utkar\anaconda3\envs\dl_project\lib\site-packages\torchvision\datasets\mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [7]:
torch.rand(1, 3, 64, 64)

tensor([[[[0.4310, 0.3708, 0.8170,  ..., 0.9311, 0.4741, 0.9214],
          [0.2027, 0.3362, 0.0866,  ..., 0.4566, 0.8995, 0.7196],
          [0.0704, 0.5182, 0.8535,  ..., 0.0459, 0.3699, 0.0949],
          ...,
          [0.8273, 0.5095, 0.3662,  ..., 0.6035, 0.2177, 0.4779],
          [0.4673, 0.0613, 0.8418,  ..., 0.7949, 0.4657, 0.2501],
          [0.8259, 0.6919, 0.5862,  ..., 0.5921, 0.6960, 0.2260]],

         [[0.3417, 0.5474, 0.9296,  ..., 0.5656, 0.3251, 0.9663],
          [0.2111, 0.4302, 0.8228,  ..., 0.4722, 0.2104, 0.6298],
          [0.3697, 0.8832, 0.3491,  ..., 0.1582, 0.8725, 0.3880],
          ...,
          [0.6661, 0.0226, 0.8084,  ..., 0.9306, 0.2303, 0.9560],
          [0.4811, 0.9657, 0.9835,  ..., 0.5560, 0.6134, 0.0407],
          [0.0766, 0.1463, 0.6798,  ..., 0.1065, 0.7414, 0.8936]],

         [[0.2568, 0.8128, 0.8995,  ..., 0.1273, 0.2458, 0.1473],
          [0.3786, 0.8419, 0.2205,  ..., 0.8336, 0.8302, 0.0721],
          [0.1971, 0.5147, 0.2671,  ..., 0

In [4]:
torch.rand(1, 1000)

tensor([[5.4611e-01, 5.5106e-01, 7.9746e-01, 7.7543e-01, 4.8453e-01, 9.7171e-01,
         9.9814e-01, 6.2213e-01, 3.9208e-02, 5.8484e-01, 1.0278e-01, 3.5993e-01,
         6.4360e-01, 1.0531e-01, 6.7521e-01, 9.0096e-01, 3.7540e-01, 7.7171e-01,
         7.2130e-02, 1.8568e-01, 6.4992e-01, 6.9994e-01, 7.9197e-01, 4.7070e-01,
         8.5741e-01, 9.5928e-01, 1.5002e-01, 9.5205e-01, 1.5343e-01, 2.3809e-01,
         9.1112e-01, 2.0444e-01, 9.9943e-01, 5.9018e-01, 8.2110e-03, 9.8063e-01,
         4.2783e-01, 3.5099e-02, 9.2064e-01, 9.7197e-02, 6.5147e-01, 3.0657e-01,
         8.6020e-01, 4.4407e-01, 1.3838e-01, 7.1260e-01, 8.7140e-02, 1.9087e-01,
         5.9806e-01, 2.9914e-01, 2.3834e-01, 4.5481e-01, 9.4442e-02, 9.2989e-01,
         5.7357e-01, 5.0749e-01, 8.9125e-01, 8.6783e-02, 3.7758e-01, 6.1112e-02,
         8.1500e-01, 8.7649e-01, 2.9217e-01, 8.3043e-01, 4.9373e-01, 6.9244e-01,
         5.9905e-01, 3.6195e-01, 6.8298e-01, 5.0089e-01, 4.1776e-02, 1.6272e-01,
         5.2796e-01, 1.3260e