<center>

# Indian Statistical Institute
## PGDBA 2020-21 1st Year 1st Semester

## Computing for Data Science
### Mid Semester Examination



### Date: 4 January 2021
</center>

<b>Submission instruction</b>: Name your file CDS.MidSem.NN.ipynb where NN stands for the last two digits of your roll number. 

In [97]:
import numpy as np

## 1.

The following code creates a 2-D numpy array (a matrix) $A$ whose entries are random non-negative integers below 10. 

In [98]:
n = 3
A = np.random.randint(10,size=(n,n))
print(A)

[[5 7 6]
 [2 2 8]
 [1 2 6]]


Complete the code below such that, 
* The 2-D array $B$ has the same shape as $A$, 
* $B[i,j] = A[i,j]^2$ if $A[i,j] > 3$, and
* $B[i,j] = 0$ otherwise.

The number of characters (apart from whitespaces) in the code should be at most 12.

<i>Hint:</i> Do not try to use a loop and run through the entries. 

<b>Example</b>:
If $A=$ 
$\left[\begin{matrix}
0 & 6 & 2 \\ 
7 & 6 & 0 \\
0 & 7 & 3
\end{matrix}\right]$,
 then $B$ should be 
$\left[\begin{matrix}
0 & 36 & 0 \\ 
49 & 36 & 0 \\
0 & 49 & 0
\end{matrix}\right]$.

In [99]:
# BEGIN CODE (at most 12 non-whitespace characters including 'B =') 
B=A*A*(A>3)
# END CODE

In [100]:
print(B)

[[25 49 36]
 [ 0  0 64]
 [ 0  0 36]]


## 2.

Let <tt>A</tt> and <tt>B</tt> be two sorted (in the ascending order) integer arrays of size $n_1$ and $n_2$ respectively. Let us assume each of these arrays contain only distinct integers.

In [143]:
# Parameters n1 and n2
n1 = 10
n2 = 15

# Creating random arrays A and B of the required sizes and sorting them first as per requirement
A = np.random.choice(n1*2, n1, replace=False)
B = np.random.choice(n2*2, n2, replace=False)
A = np.sort(A)
B = np.sort(B)
print(A)
print(B)

[ 0  3  5 10 11 12 13 14 17 18]
[ 0  2  4  8  9 11 12 16 17 18 20 22 24 26 29]


Let us define the exclusive or (XOR) of two sets $A$ and $B$ as the set of elements which are present in one of the sets, but not both. In other words, $\mathrm{XOR}(A,B) = (A \cup B) - (A \cap B)$.

Write a function to compute the <tt>XOR</tt> of two such integer arrays. The complexity of your code should be $O(n_1 + n_2)$. 

<i>Example:</i> If <tt>A = [1,3,5,7]</tt> and <tt>B = [3,6,9]</tt>, then <tt>XOR(A,B)</tt> should be <tt>[1,5,6,7,9]</tt>.

### Approach 1 : make a big list and return unique value

In [144]:
# Approach 1 : make a big list and return unique value

# unique will do sorting so it can take O(logn) or O(n2)


def xor(A,B):
    return np.unique(np.append(A,B))

In [145]:
# Test the code
print(xor(A,B))

[ 0  2  3  4  5  8  9 10 11 12 13 14 16 17 18 20 22 24 26 29]


### Approach 2

###  Step 1: Append both list to form a big list (O(n1+n2) in space and time)
###  Step 2: make a dictionary  of values in list (O(n1+n2) in space and time)
###  Step 3:return elements with dict values as 1 (O(1) in time as it is lookup from hashtable)
###  Overall complexity O(n1+n2)

###  Pseudo code is given

In [149]:
# Approach 2

# Step 1: Append both list to form a big list (O(n1+n2) in space and time)
# Step 2: make a dictionary  of values in list (O(n1+n2) in space and time)
# Step 3:return elements with dict values as 1 (O(1) in time as it is lookup from hashtable)
# Overall complexity O(n1+n2)

# This is a pseudo code

def xor(A,B):
    c = np.append(A,B)
    my_dictionary = {}
    xor = []
    for i in range(len(c)):
        if(my_dictionary.get(i)==None):
            my_dictionary[i]=1
        else:
            my_dictionary[i]=my_dictionary[i]+1
    for key, value in my_dictionary.items():
        if(value == 1):
            xor.append(key)
    return xor


In [150]:
# Test the code
print(xor(A,B))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [153]:
my_dictionary = {1:2,3:1,4:2}

c=[1,5,7,7,2]

for i in range(len(c)):
        if(my_dictionary.get(i)==None):
            my_dictionary[i]=1
        else:
            my_dictionary[i]=my_dictionary[i]+1

In [162]:
my_dictionary = {}

if(my_dictionary.get(1)==None):
    print("not found")
    my_dictionary[1]=1
    
my_dictionary[1]

not found


1

In [157]:
my_dictionary.get(1)

xor = []
for key, value in my_dictionary.items():
    print(key,value)
    if(value == 1):
            xor.append(key)
# for key in my_dictionary:
#     print(key,my_dictionary(key))
xor

[]

## 3. 

Given a $3 \times n$ matrix$A$ with rank $3$ ($3 \leq n$), write a function to choose $3$ columns from $A$ to form a basis of $\mathbb{R}^3$. You are free to use functions from numpy. Return your choice of columns in matrix the $3 \times 3$ matrix $B$.

### Approach

### Step1: Select any of 3 columns of the matrix (nC3 combination of columns)
### Step2: Create a 3X3 Matrix with above selected three columns
### Step3: Calculate Determinant if it is non zero then columns are linearly independent and will span R3 space
### Step4: Return the matrix with these 3 columns

In [106]:
# Approach

# Step1: Select any of 3 columns of the matrix (nC3 combination of columns)
# Step2: Create a 3X3 Matrix with above selected three columns
# Step3: Calculate Determinant if it is non zero then columns are linearly independent and will span R3 space 
# Step4: Return the matrix with these 3 columns

def basis(A):
    AT = np.transpose(A)
    for i in range(AT.shape[0]-2):                      #First vector from any first n-2 column
        for j in range (i+1, AT.shape[0]-1):            #Second vector from beyond the 1st chosen column to n-1th column
            for k in range(j+1,AT.shape[0]):            #Third vector from beyond the 2nd chosen column to nth column    
                B = np.array([AT[i],AT[j],AT[k]])       # In this way we see all nC3 combination
                if(np.linalg.det(B)!=0):            # We return the first time we encounter 3 columns with non zero determinant
                    return np.transpose(B)

In [107]:
n = 30
A = np.random.randint(10,size=(3,n))
print(A)

B = basis(A)
print(B)

[[9 5 7 9 5 1 6 8 8 4 8 2 2 9 4 3 5 2 1 8 9 7 6 2 5 5 2 7 4 3]
 [1 1 0 9 6 2 8 3 5 9 4 8 5 3 1 7 7 1 8 5 7 9 5 2 7 5 9 6 6 4]
 [4 4 3 1 1 9 8 2 8 0 2 1 6 3 5 9 2 9 3 9 7 1 2 1 7 9 9 8 2 3]]
[[9 5 7]
 [1 1 0]
 [4 4 3]]


In [108]:
# Some Rough work for writing above function



# AT = np.transpose(A)
# AT.shape[0]

# print(AT[0])

# B= np.array([AT[0],AT[1],AT[2]])

# print(B)

# print(np.linalg.det(B))

# print(np.array(range(AT.shape[0]-2)))